# Generated by Django 4.2.16 on 2024-10-26 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='image',
            field=models.ImageField(blank=True, upload_to='contests_images', verbose_name='Изображение'),
        ),
    ]
